baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "toha"
[markup]
  [markup.highlight]
    noClasses = true
    style = 'monokai'
    lineNos = true
    
[params]
  enableBlogPost = true
