baseURL = 'https://elegant-jelly-5132b5.netlify.app/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "toha"
[markup]
  [markup.highlight]
    noClasses = true
    style = 'monokai'
    lineNos = true
    
[params]
  enableBlogPost = true
